### ISSUE TITLE
Hi I am new here please teach me how to use it..

### ISSUE THREAD

**Issue by Sayuk49** [cryptax/angeapk#3]

**Comment by cryptax** [comment]
Please have a look at these resources:

- Paper: https://www.blackhat.com/docs/eu-14/materials/eu-14-Apvrille-Hide-Android-Applications-In-Images-wp.pdf
- Slides: https://www.blackhat.com/docs/eu-14/materials/eu-14-Apvrille-Hide-Android-Applications-In-Images.pdf

I should add that this probably does not work as such on recent Android versions.
Enjoy,
