### ISSUE TITLE
Problem when I try to use DexClassLoader

### ISSUE THREAD

**Issue by ferdinan4** [cryptax/angeapk#5]
Hi Axelle,

I have been following the angeAPK talk. However ,I faced with some issues when I tried to use DexClassLoader.

I would like to unpack and load the dynamic code in the application activity, I was able to get the payloadapk, however when I try to load in the next method **loadAPK():** the application crashes and gives me this exception: 

**_java.lang.ClassNotFoundException: Didn't find class "com.example.cryptedv2.StringXORed" on path: DexPathList[[zip file "/storage/emulated/0/hidden.apk"],nativeLibraryDirectories=[/system/lib]]_**

`        private void loadApk(String apkPath) {

        String className = "com.example.cryptedv2.StringXORed"; //modify to new one
        String methodToInvoke = "getFlagEncrypt"; //Modificar to new one

        Log.v("loadDexClasses", "Dex Preparing to loadDexClasses!");

        File dexOpt = this.getDir("dexOpt", MODE_PRIVATE);
        final DexClassLoader classloader = new DexClassLoader(
                apkPath,
                dexOpt.getAbsolutePath(),
                null,
                this.getClassLoader());

        Log.v("loadDexClasses", "Searching for class : "
                + "com.registry.Registry");
        try {
            Class<?> classToLoad = (Class<?>) classloader.loadClass(className);
            Object instance = classToLoad.newInstance();
            Method method = classToLoad.getMethod(methodToInvoke);
            String flag = (String) method.invoke(instance);
        } catch (IllegalAccessException e) {
            e.printStackTrace ();
        } catch (ClassNotFoundException e) {
            e.printStackTrace ();
        } catch (NoSuchMethodException e) {
            e.printStackTrace ();
        } catch (InvocationTargetException e) {
            e.printStackTrace ();
        } catch (InstantiationException e) {
            e.printStackTrace ();
        }
`

I tried to obfuscated also a .dex file of the application but it is also throwing the same exception.

Thanks in advance,

Fernando

**Comment by cryptax** [comment]
Hello Fernando,
In `DexClassLoader`, the first argument should be the path to the DEX file (`classes.dex`), not a path to an APK (`DexPathList[[zip file "/storage/emulated/0/hidden.apk"]`)

**Comment by ferdinan4** [comment]
Hi Axelle,

I solve it using an apk with the same package of the actual:

  final File optimizedDexOutputPath = getDir("outdex", 0);

            DexClassLoader dLoader = new DexClassLoader(wrapper.PAYLOAD_APK,optimizedDexOutputPath.getAbsolutePath(),
                    null,ClassLoader.getSystemClassLoader().getParent());
            Class<?> loadedClass = dLoader.loadClass(className);
            Object obj = (Object)loadedClass.newInstance();
            Method m = loadedClass.getMethod(methodToInvoke);
            
  Where wrapper.PAYLOAD_APK --> is the apk path.
  
  I do not know why this doesn't works with other package names, should I add the new classes in the Manifest?
  
  You can close the issue.
  
  Thanks in advance,
  
  Fernando
